version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=ecommerce_db"
      - "POSTGRES_PASSWORD=postgres"
    expose:
      - "5432"
    ports:
      - "5434:5432"
  