export const USER_EXIST = 'USER_EXIST';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_NOT_ACTIVED = 'USER_NOT_ACTIVED';
export const USER_PASS_EMPTY = 'USER_PASS_EMPTY';
export const USER_PASS_ALREADY_DEFINED = 'USER_PASS_ALREADY_DEFINED';

export const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';

export const INVALID_PASSWORD = 'INVALID_PASSWORD';

export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
